# This is required due to https://www.drupal.org/node/3489785,
# https://www.drupal.org/project/drupal/issues/3477043 and
# https://www.drupal.org/project/drupal/issues/3447617
langcode: en
status: true
dependencies:
  module:
    - node
    - text
id: node.body
field_name: body
entity_type: node
type: text_with_summary
settings: {  }
module: text
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: true
custom_storage: false
